---
- name: Instalar e iniciar Nginx na EC2 AWS
  hosts: aws_ec2
  become: yes
  vars:
    ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/Documentos/aws-credentials/keys/ec2-instance.pem"
    ansible_user: ec2-user
  tasks:
    - name: Atualizar pacotes
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == 'RedHat'

    - name: Instalar Nginx
      yum:
        name: nginx
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Iniciar e habilitar Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
      when: ansible_os_family == 'RedHat'

    - name: Abrir porta 80 no firewall (caso firewalld esteja ativo)
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
        immediate: yes
      when: ansible_os_family == 'RedHat'
        and ansible_facts.services['firewalld.service'] is defined
        and ansible_facts.services['firewalld.service'].state == 'running'

    - name: Criando página inicial personalizada
      copy:
        src: ../pages/index.html
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: root
        mode: '0644'

    - name: Garantir que o diretório styles existe
      file:
        path: /usr/share/nginx/html/styles
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Aplicando estilos personalizados
      copy:
        src: ../pages/styles/style.css
        dest: /usr/share/nginx/html/styles/style.css
        owner: root
        group: root
        mode: '0644'
      notify:
        - Reiniciar Nginx

  handlers:
    - name: Reiniciar Nginx
      systemd:
        name: nginx
        state: restarted
      when: ansible_os_family == 'RedHat'
